from django.db import models
import uuid


class Conversation(models.Model):
    """A single chat session. user_id is a session key (no auth required)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session_key = models.CharField(max_length=64, db_index=True)
    title = models.CharField(max_length=200, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Conversation({self.id}, {self.title or 'Untitled'})"


class Message(models.Model):
    """A single turn in a conversation (either user or assistant)."""
    ROLE_CHOICES = [("user", "User"), ("assistant", "Assistant")]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    conversation = models.ForeignKey(
        Conversation, on_delete=models.CASCADE, related_name="messages"
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    text = models.TextField()
    # chart_path = models.CharField(max_length=500, blank=True, default="")
    details_json = models.JSONField(default=list)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"Message({self.role}, {self.text[:50]})"

    @property
    def query_log(self):
        return self.query_logs.first()

    @property
    def details_json_str(self):
        import json
        return json.dumps(self.details_json)

class QueryLog(models.Model):
    """
    Logs every SQL query generated by the agent.
    Resume gold: "I logged every generated SQL with latency, status, and error text."
    """
    STATUS_CHOICES = [
        ("success", "Success"),
        ("blocked", "Blocked by safety"),
        ("error", "Execution error"),
        ("empty", "No rows returned"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    message = models.ForeignKey(
        Message, on_delete=models.CASCADE, related_name="query_logs"
    )
    generated_sql = models.TextField(blank=True, default="")
    rows_returned = models.IntegerField(default=0)
    execution_ms = models.IntegerField(default=0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="success")
    error_text = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"QueryLog({self.status}, {self.rows_returned} rows, {self.execution_ms}ms)"
