# Generated by Django 4.2.17 on 2026-07-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='details_json',
            field=models.JSONField(default=list),
        ),
    ]
