# Generated by Django 4.2.17 on 2026-07-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_details_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='chat.message'),
        ),
    ]
