# Generated by Django 4.2.17 on 2026-07-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_querylog_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chart_path',
        ),
    ]
